name: auto-georef-project
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.7
  - pip

  # AWS
  - boto3

  # Core scientific python
  - numpy
  - matplotlib
  - pyqt
  - seaborn
  - tqdm
  - kiwisolver

  # Spatial packages
  #- rasterio
  - pysal
  - pyproj
  - rasterstats
  - geopy
  - cartopy

  #- geopandas
  - contextily
  - earthpy
  - folium
  - geojson
  - mapboxgl
  - hydrofunctions
  - geocoder
  - tweepy

  # Natural language processing
  - nltk
  - textblob

  # Jupyter Environment
  - jupyter
  - papermill
  - autopep8
  - jupyterlab
  - notebook
  - ipython
  - jupyter_contrib_nbextensions
  - nbclean

  # For image cleaning
  - opencv

  - pip:
    - enum
